module.exports = [
  require('./init'),
  require('./add-endpoint'),
  require('./add-project'),
  require('./get-schema'),
  require('./schema-status'),
  require('./create'),
  require('./ping'),
  require('./query'),
  require('./diff'),
  require('./playground'),
  require('./lint'),
  require('./codegen'),
  require('graphql-cli-prepare'),
]
